name: Run Tests and Deploy

on:
  push:
    branches:
      - master
      - develop  # Runs on push to master or develop branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up Node.js environment
        with:
          node-version: '16'  # Node.js version

      - name: Install Dependencies
        run: npm install  # Install the necessary npm packages

      - name: Run Tests
        run: npm test -- --coverage  # Run tests and generate coverage report

      - name: List Coverage Directory
        run: ls -R coverage  # Check if the coverage directory is generated successfully

  deploy:
    needs: test  # This ensures the deploy job only runs after the 'test' job passes
    runs-on: ubuntu-latest
    if: success()  # Only runs if the 'test' job was successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code to deploy

      - name: Deploy to GitHub Pages for coverage
        uses: peaceiris/actions-gh-pages@v3  # Action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GH_PAT }}  # Use the GitHub Personal Access Token (or default token)
          publish_dir: coverage  # The directory to deploy (coverage report)
          user_name: 'Yousaf Raza'  # GitHub username for commit author
          user_email: 'your-email@example.com'  # Email for commit author (replace with your email)
          commit_message: 'Deploy coverage report'  # Custom commit message
