name: Test and Deploy Reports

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Example: Install dependencies
    - name: Install dependencies
      run: npm install

    # Example: Run tests and generate reports
    - name: Run tests
      run: npm test

    # Gather all the files you want to publish
    - name: Prepare test report for gh-pages
      run: mv ./path/to/test/report/* ./public/

    # Deploy to GitHub Pages
    - name: Deploy test report to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/
        publish_branch: gh-pages
        force_orphan: true